ALTER TABLE `dvi_itinerary_plan_hotel_details`
  ADD COLUMN `hotel_provider` VARCHAR(32) NULL,
  ADD COLUMN `hotel_booking_mode` VARCHAR(32) NULL,
  ADD COLUMN `price_source` VARCHAR(32) NULL,
  ADD COLUMN `is_live_rate` TINYINT(1) NULL,
  ADD COLUMN `selected_rate_option_id` VARCHAR(255) NULL,
  ADD COLUMN `selected_price_per_night` FLOAT NULL,
  ADD COLUMN `selected_total_price` FLOAT NULL,
  ADD COLUMN `selected_currency` VARCHAR(8) NULL,
  ADD COLUMN `selected_price_snapshot` LONGTEXT NULL,
  ADD COLUMN `hotel_approval_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_REQUESTED',
  ADD COLUMN `hotel_approval_requested_at` DATETIME NULL,
  ADD COLUMN `hotel_approval_requested_by` INT NULL,
  ADD COLUMN `hotel_approved_at` DATETIME NULL,
  ADD COLUMN `hotel_approved_by` INT NULL,
  ADD COLUMN `hotel_rejected_at` DATETIME NULL,
  ADD COLUMN `hotel_rejected_by` INT NULL,
  ADD COLUMN `hotel_approval_notes` TEXT NULL,
  ADD COLUMN `manual_confirmation_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED',
  ADD COLUMN `manual_confirmation_requested_at` DATETIME NULL,
  ADD COLUMN `manually_confirmed_at` DATETIME NULL,
  ADD COLUMN `manually_confirmed_by` INT NULL,
  ADD COLUMN `manual_confirmation_notes` TEXT NULL,
  ADD COLUMN `requires_price_reacceptance` TINYINT(1) NOT NULL DEFAULT 0,
  ADD INDEX `idx_itinerary_plan_hotel_approval_status` (`hotel_approval_status`),
  ADD INDEX `idx_itinerary_plan_hotel_manual_confirmation_status` (`manual_confirmation_status`);

ALTER TABLE `dvi_confirmed_itinerary_plan_hotel_details`
  ADD COLUMN `hotel_provider` VARCHAR(32) NULL,
  ADD COLUMN `hotel_booking_mode` VARCHAR(32) NULL,
  ADD COLUMN `price_source` VARCHAR(32) NULL,
  ADD COLUMN `is_live_rate` TINYINT(1) NULL,
  ADD COLUMN `selected_rate_option_id` VARCHAR(255) NULL,
  ADD COLUMN `selected_price_per_night` FLOAT NULL,
  ADD COLUMN `selected_total_price` FLOAT NULL,
  ADD COLUMN `selected_currency` VARCHAR(8) NULL,
  ADD COLUMN `selected_price_snapshot` LONGTEXT NULL,
  ADD COLUMN `hotel_approval_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_REQUESTED',
  ADD COLUMN `hotel_approval_requested_at` DATETIME NULL,
  ADD COLUMN `hotel_approval_requested_by` INT NULL,
  ADD COLUMN `hotel_approved_at` DATETIME NULL,
  ADD COLUMN `hotel_approved_by` INT NULL,
  ADD COLUMN `hotel_rejected_at` DATETIME NULL,
  ADD COLUMN `hotel_rejected_by` INT NULL,
  ADD COLUMN `hotel_approval_notes` TEXT NULL,
  ADD COLUMN `manual_confirmation_status` VARCHAR(32) NOT NULL DEFAULT 'NOT_STARTED',
  ADD COLUMN `manual_confirmation_requested_at` DATETIME NULL,
  ADD COLUMN `manually_confirmed_at` DATETIME NULL,
  ADD COLUMN `manually_confirmed_by` INT NULL,
  ADD COLUMN `manual_confirmation_notes` TEXT NULL,
  ADD COLUMN `requires_price_reacceptance` TINYINT(1) NOT NULL DEFAULT 0,
  ADD INDEX `idx_cnf_itinerary_plan_hotel_approval_status` (`hotel_approval_status`),
  ADD INDEX `idx_cnf_itinerary_plan_hotel_manual_confirmation_status` (`manual_confirmation_status`);

CREATE TABLE `dvi_itinerary_plan_hotel_approval_history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `itinerary_plan_hotel_details_id` INT NOT NULL,
  `previous_approval_status` VARCHAR(32) NULL,
  `new_approval_status` VARCHAR(32) NOT NULL,
  `previous_confirmation_status` VARCHAR(32) NULL,
  `new_confirmation_status` VARCHAR(32) NOT NULL,
  `price` FLOAT NULL,
  `currency` VARCHAR(8) NULL,
  `notes` TEXT NULL,
  `acted_by` INT NULL,
  `acted_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `metadata` LONGTEXT NULL,
  PRIMARY KEY (`id`),
  INDEX `idx_hotel_approval_history_selection` (`itinerary_plan_hotel_details_id`),
  INDEX `idx_hotel_approval_history_status` (`new_approval_status`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
