-- Export hotel 44578 from production for local update
SELECT 
  44578 as hotel_id,
  hotel_name,
  hotel_code,
  tbo_hotel_code,
  tbo_city_code,
  resavenue_hotel_code,
  hotel_mobile,
  hotel_email,
  hotel_country,
  hotel_city,
  hotel_state,
  hotel_place,
  hotel_address,
  hotel_pincode,
  hotel_margin,
  hotel_margin_gst_type,
  hotel_margin_gst_percentage,
  hotel_longitude,
  hotel_latitude,
  hotel_category,
  hotel_cancel_policy,
  hotel_power_backup,
  hotel_free_cancel_policy_no_of_days_from_booking_date,
  hotel_cancel_policy_percentage,
  hotel_hotspot_status,
  axisrooms_property_id,
  axisrooms_enabled,
  staah_property_id,
  staah_enabled,
  status
FROM dvi_hotel 
WHERE hotel_id = 44578;
