CREATE TABLE IF NOT EXISTS dvi_payment_transaction (
  payment_transaction_ID INT AUTO_INCREMENT PRIMARY KEY,
  flow_type VARCHAR(64) NOT NULL,
  entity_id INT NOT NULL DEFAULT 0,
  subscription_plan_id INT NOT NULL DEFAULT 0,
  amount_inr FLOAT NOT NULL DEFAULT 0,
  amount_paise INT NOT NULL DEFAULT 0,
  currency VARCHAR(10) NOT NULL DEFAULT 'INR',
  provider VARCHAR(30) NOT NULL DEFAULT 'razorpay',
  provider_order_id VARCHAR(120) NOT NULL,
  provider_payment_id VARCHAR(120) NULL,
  provider_signature VARCHAR(255) NULL,
  receipt VARCHAR(120) NULL,
  status_code INT NOT NULL DEFAULT 0,
  processed TINYINT NOT NULL DEFAULT 0,
  processed_on DATETIME NULL,
  error_message TEXT NULL,
  metadata JSON NULL,
  createdby INT NOT NULL DEFAULT 0,
  createdon DATETIME NULL,
  updatedon DATETIME NULL,
  status TINYINT NOT NULL DEFAULT 1,
  deleted TINYINT NOT NULL DEFAULT 0,
  INDEX idx_payment_txn_flow (flow_type),
  INDEX idx_payment_txn_entity (entity_id),
  INDEX idx_payment_txn_order (provider_order_id),
  INDEX idx_payment_txn_payment (provider_payment_id),
  INDEX idx_payment_txn_status_code (status_code),
  INDEX idx_payment_txn_processed (processed),
  INDEX idx_payment_txn_deleted (deleted)
);
